version: "3.3"
services:
  mysql:
    image: "mysql:5.7"
    container_name: mysql
    environment:
      - MYSQL_DATABASE=lportal
      - MYSQL_PASSWORD=passw0rd
      - MYSQL_ROOT_PASSWORD=passw0rd
      - MYSQL_USER=dxpcloud
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --character-set-filesystem=utf8 --max_allowed_packet=32M
    ports:
      - "3306:3306"
    ulimits:
      nofile: 262144
    volumes:
      - type: bind
        source: ./mysql/docker-entrypoint-initdb.d
        target: /docker-entrypoint-initdb.d
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -P 3306 -u dxpcloud -ppassw0rd
  postgres:
    image: "postgres:15.2"
    container_name: postgres
    healthcheck:
      test: pg_isready
    environment:
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_USER=dxpcloud
      - POSTGRES_DB=lportal
    ports:
      - "5432:5432"
  pgloader:
    build:
      context: pgloader
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
      postgres:
        condition: service_healthy
        restart: true
